pattern-lab/patternlab-node

builder/patternlab.js

Guard against index out of bounds errors in View All Nav logic

---

builder/pattern_assembler.js

Ref issue #153 
Just a change in the order of execution. Please review, comment, and merge.

Better ordering of pattern variants in toolbar menu

---

builder/pattern_assembler.js
builder/pseudopattern_hunter.js
test/list_item_hunter_tests.js

Ref issue #150 
I think the code is fairly well commented and would therefore speak for how it's trying to accomplish what is wanted in the issue. Please review, comment, and merge.

update mergeData() so that 2nd param has priority over 1st

---

README.md

It's a pleasure to contribute, even in a small way :D
I'm a big fan of Pattern Lab -- been using it on projects for two years.

Remove extra/unnecessary word

---

CHANGELOG
builder/lineage_hunter.js
builder/list_item_hunter.js
builder/media_hunter.js
builder/object_factory.js
builder/parameter_hunter.js
builder/pattern_assembler.js
builder/pattern_exporter.js
builder/patternlab.js
builder/patternlab_grunt.js
builder/patternlab_gulp.js
builder/pseudopattern_hunter.js
builder/style_modifier_hunter.js
package.gulp.json
package.json

closes #242
also updates glob dependency

Pattern Lab Node 1.1.1

---

CHANGELOG
builder/lineage_hunter.js
builder/list_item_hunter.js
builder/media_hunter.js
builder/object_factory.js
builder/parameter_hunter.js
builder/pattern_assembler.js
builder/pattern_exporter.js
builder/patternlab.js
builder/patternlab_grunt.js
builder/patternlab_gulp.js
builder/pseudopattern_hunter.js
builder/style_modifier_hunter.js
package.gulp.json
package.json

Addresses #217 which was closed prematurely. this PR resolves the gap with PL PHP

Support for pattern type view all pages

---

Gruntfile.js
package.gulp.json

Here's a quick PR that should get Travis tests working again and also fixes `package.gulp.json`. Diving into some more testing too! :)

pattern engines tweaks

---

core/lib/lineage_hunter.js
core/lib/list_item_hunter.js
core/lib/media_hunter.js
core/lib/object_factory.js
core/lib/parameter_hunter.js
core/lib/pattern_assembler.js
core/lib/pattern_exporter.js
core/lib/patternlab.js
core/lib/patternlab_grunt.js
core/lib/patternlab_gulp.js
core/lib/pseudopattern_hunter.js
core/lib/style_modifier_hunter.js
package.gulp.json
package.json

#300 Dev >>>> Dev 2.0

---

core/lib/lineage_hunter.js
core/lib/list_item_hunter.js
core/lib/media_hunter.js
core/lib/object_factory.js
core/lib/parameter_hunter.js
core/lib/pattern_assembler.js
core/lib/pattern_exporter.js
core/lib/patternlab.js
core/lib/patternlab_grunt.js
core/lib/patternlab_gulp.js
core/lib/pseudopattern_hunter.js
core/lib/style_modifier_hunter.js
package.gulp.json
package.json

Pattern Lab 1.2.2

---

Gruntfile.js
core/lib/lineage_hunter.js
core/lib/list_item_hunter.js
core/lib/media_hunter.js
core/lib/object_factory.js
core/lib/parameter_hunter.js
core/lib/pattern_assembler.js
core/lib/pattern_exporter.js
core/lib/patternlab.js
core/lib/patternlab_grunt.js
core/lib/patternlab_gulp.js
core/lib/pseudopattern_hunter.js
core/lib/style_modifier_hunter.js
core/lib/ui_builder.js
core/lib/utilities.js
package.json

Updating dependencies to latest thanks to `ncu`
The debatable one would be twig, since that and the other engines will be removed at some point.
@geoffp please help weigh in on that point and test if you have time.

updating dependencies

---

core/lib/patternlab.js
package.json

https://github.com/pattern-lab/patternlab-node/issues/332.
moved wip edition-node-gulp code in https://github.com/pattern-lab/edition-node-gulp/commit/6e0d49748900c311f67375eb951fc71b8cfdfb80

moved head and foot management code

---

core/lib/patternlab.js
core/lib/starterkit_manager.js

to use:
`npm pattern-lab/starterkit-mustache-bootstrap` or any kit with a package.json or npm destination
`gulp patternlab:starterkit-load --kit=starterkit-mustache-bootstrap`

Basic Starterkit manager support

---

package.json

removing direct dependencies

---

.github/ISSUE_TEMPLATE.md

* mention gitter channel as a resource to go to first
* prompt user for Edition version and Node version

updating issue template

---

core/lib/markdown_parser.js
core/lib/pattern_assembler.js
core/lib/patternlab.js
package.json
test/files/_patterns/00-test/00-foo.md
test/files/_patterns/00-test/01-bar.md
test/files/annotations.md
test/markdown_parser_tests.js
test/style_modifier_hunter_tests.js

- Parses markdown even when no frontmatter exists 
- No longer attempts to strip quotes from frontmatter values
- Unit test coverage

Pattern Lab Node 2.1.1

---

core/lib/pattern_assembler.js

Addresses output found here: https://travis-ci.org/pattern-lab/patternlab-node/jobs/142759094
- travis falsly reports a TON of errors in the output

alter check for error to attempt to be cross-platform

---

core/lib/markdown_parser.js
core/lib/pattern_assembler.js
core/lib/patternlab.js
package.json
test/lineage_hunter_tests.js
test/pattern_assembler_tests.js

- Does not yet display on main styleguide screen

Pattern Lab Node 2.2.0

---

core/lib/parameter_hunter.js

Addresses #
@bmuenzenmeyer Just a minor typo fix.

paramToJson-typo-fix

---

test/engine_underscore_tests.js

No biggie. Just an extra unit test for the underscore engine that I needed to get lineage hunting right.

Underscore unit test

---

core/lib/patternlab.js
package.json

Pattern Lab Node Core 2.4.2

---

core/lib/patternlab.js
core/lib/ui_builder.js
package.json
test/ui_builder_tests.js

https://github.com/pattern-lab/patternlab-node/wiki/ChangeLog

Pattern Lab Node Core 2.4.4

---

README.md

update typo in readme

---

core/lib/utilities.js

Addresses #492
Added JSDoc comments to all utility methods

#492 add jsdoc comments to core/lib/utilities.js

---

test/lineage_hunter_tests.js

Convert lineage_hunter_tests.js to use tap/ tape

---

test/list_item_hunter_tests.js

Convert list_item_hunter.js to use tap/tape

---

test/markdown_parser_tests.js

Convert markdown_parser_tests.js to use tap/tape

---

test/parameter_hunter_tests.js

Convert parameter_hunter_tests.js to use tap/tape

---

test/pattern_assembler_tests.js

Convert pattern_assembler_tests.js to use tap/tape

---

test/pattern_engines_tests.js

Convert pattern_engines_tests.js to use tap/tape

---

test/patternlab_tests.js

Convert patternlab_tests.js to use tap/tape

---

test/pseudopattern_hunter_tests.js

Convert pseudopattern_hunter_tests.js to use tap/tape

---

test/style_modifier_hunter_tests.js

Convert style_modifier_hunter_tests.js to use tap/tape

---

test/ui_builder_tests.js

Convert ui_builder_tests.js to use tap/tape

---

core/lib/pattern_assembler.js
core/lib/ui_builder.js

Sort the patterns array before building navigation!

---

.npmignore

add npmignore file

---

core/lib/patternlab.js
package.json

Pattern Lab Node Core 2.7.2

---

README.md

Fixed Slack channel link

---

.github/stale.yml

Addresses #698
Summary of changes: Gonna give stale bot https://probot.github.io/apps/stale/ a try!

configured stale bot

---

core/lib/ui_builder.js

Addresses #700 
Passes theme to client via `patternlab-data.json`

700 theme config

---

package-lock.json

add package-lock.json support

---

README.md

closes #728
Adds coveralls badge

feat(README): Add coveralls badge to README

---

patternlab-config.json
test/util/patternlab-config.json

feat(package): Add default theme config to patternlab-config.json

---

.travis.yml
core/lib/pattern_engines.js
package.json

Addresses #735
- Engine load now supports [@pattern-lab scoped packages](npmjs.com/org/pattern-lab)
- Added scoped packages to Travis CI

Pattern Lab Node Core Alpha 4

---

README.md

- Changes the link to the config wiki inside README.md
- Fixes #747

Updating readme entry for config wiki

---

core/index.js
core/lib/buildFooter.js
core/lib/patternlab.js
core/lib/processMetaPattern.js
core/lib/ui_builder.js

Addresses #766
Supersedes https://github.com/pattern-lab/patternlab-node/pull/770 - which had a conflict

Danwhite85 issue/766 engine meta files

---

package-lock.json
package.json

Adds [standard-version](https://github.com/conventional-changelog/standard-version)

feat(package): Add standard version

---

test/util/patternlab-config.json

part of https://github.com/pattern-lab/patternlab-node/issues/745
* Prettier also touched this file.

fix(test configuration): Remove vestigial configuration entries

---

.prettierignore
package-lock.json
package.json
packages/cli/package-lock.json
packages/core/package.json
packages/live-server/package-lock.json
packages/live-server/package.json
packages/plugin-tab/package.json

Part of #815 
* hoists common devDependencies so we are on the same version of eslint* and prettier
* excludes tests from code coverage

More cleanup

---

lerna.json
package-lock.json
package.json

Closes #854
Summary of changes: Adds `lerna-changelog` as another top level tool. Adding this in hopes of making the documentation of change easier for users to follow.

feat(package): add lerna-changelog

---

packages/cli/.gitattributes
packages/cli/.gitignore
packages/cli/bin/archive.js
packages/cli/bin/ask.js
packages/cli/bin/build.js
packages/cli/bin/cli-actions/build.js
packages/cli/bin/cli-actions/help.js
packages/cli/bin/cli-actions/init.js
packages/cli/bin/cli-actions/version.js
packages/cli/bin/copy-source-files.js
packages/cli/bin/inquiries/edition.js
packages/cli/bin/patternlab.js
packages/cli/bin/replace-config.js
packages/cli/bin/resolve-config.js
packages/cli/bin/scaffold.js
packages/cli/bin/serve.js
packages/cli/readme.md
packages/cli/test/cli-init.test.js

Closes #819 
Also attempts to fix line endings for the entry point of the CLI

Cli line endings

---

packages/cli/bin/cli-actions/version.js

Closes #862 
Fixes arrow func not returning a value.

Fixes undefined return in @pattern-lab/cli version.js

---

packages/cli/bin/install-edition.js

Closes #863 
- Adding scripts to package.json after installing `@pattern-lab/edition-node`

Adding edition scripts to package.json after installing edition

---

README.md

This fixes the stretched logo on small screens.

fix: adjust logo sizing in readme

---

packages/core/src/lib/compose.js

Closes #947 
Summary of changes: Add cachebuster to allFooterData

Add cachebuster to allFooterData

---

CODEOWNERS

Closes #911 
Adds CODEOWNERS file

Benhalverson codeowners

---

CODEOWNERS

#911
Summary of changes: Added the codeowners file
I'm looking for some feedback on who owns what.

docs(CODEOWNERS file): created the code owners file

---

packages/cli/package.json
packages/core/package.json
packages/engine-handlebars/package.json
packages/engine-mustache/package.json
packages/live-server/package.json

Updated dependencies of different packages while they have npm audits for lodash, tap and even a critical with the handlebars package.

Feature update dependencies

---

packages/uikit-workshop/package.json

Closes #1086 
* adds needed folders and webpack config to published bundle

1086 deploy files

---

packages/starterkit-handlebars-demo/dist/css/scss/abstracts/_typography.scss

Fix what seems like c/p artifact

fix(docs): Update docs in _typography.scss

---

packages/engine-twig/package.json
yarn.lock

* Update dependency on twing JS engine

fix: Update dependency on twing JS engine

---

packages/uikit-workshop/src/scripts/components/prism-languages.js

For the update made in #1166 I missed the JSON and typescript highlighting.
Will be implemented with this pr.

Add additional tab language highlighting
