Gruntfile.js, package.json, source/_patternlab-files/pattern-header-footer/footer.html, source/_patternlab-files/styleguide.mustache
Added browsersync to the Gruntfile, should automatically start up now.  You can open the same url with different devices/browsers and it will sync your scrolling and auto refresh devices so that you can sync looking at your styles while working on them.
Currently Ios doesnt sync with scrolling, but it will auto refresh with the rest of the devices.
Because of the way the navigation works, it doesn't currently support syncing the moving between pages, there might be a way to solve this though.
I changed the 'connect' hostname to be your public wifi address so that your devices could access patternlab, but left the hostname line commented in if you want to opt out of having your styleguide available over Wifi.
Sorry about the messy Gruntfile commit, my javascript formatter on save …
=> Added BrowserSync

.gitignore, CHANGELOG, builder/lineage_hunter.js, builder/media_hunter.js, builder/object_factory.js, builder/pattern_exporter.js, builder/patternlab.js, builder/patternlab_grunt.js, package.json, source/css/scss/base/_global-classes.scss, source/css/style.css, test/media_hunter_tests.js
=> patternlab node 0.8.1 release

CHANGELOG, Gruntfile.js, README.md, builder/lineage_hunter.js, builder/list_item_hunter.js, builder/media_hunter.js, builder/object_factory.js, builder/parameter_hunter.js, builder/pattern_assembler.js, builder/pattern_exporter.js, builder/patternlab.js, builder/patternlab_grunt.js, builder/pseudopattern_hunter.js, package.json, public/styleguide/js/styleguide.js, source/_patterns/02-organisms/02-comments/00-comment-thread.mustache, test/list_item_hunter_tests.js, test/object_factory_tests.js
=> Dev to Master

builder/parameter_hunter.js, builder/pattern_assembler.js, test/parameter_hunter_tests.js, test/pattern_assembler_tests.js
Updating regexes and key options to allow for explicit paths to be used in Mustache partial tags. Referenced in issue #146
=> more-flexible-mustache-partial-syntax

builder/list_item_hunter.js, test/list_item_hunter_tests.js
@bmuenzenmeyer I overlooked this part of the code when allowing the more verbose Mustache partial syntax. Hopefully, we got all of them :smiley: 
Please review, comment, and merge.
=> allowing verbose partials for list items

gulpfile.js
Fixes issue #227 "gulpfile: style.css not copied after clean install & browser-sync watching wrong css directory".
=> Fix gulpfile issues with copying and watching css files.

builder/patternlab.js, test/pattern_assembler_tests.js
That, and kill more `file.substring(2)`s that were a potential source of errors.
=> Root out a few more hard-coded paths

builder/patternlab.js, package.gulp.json, package.json
OK, so here's the absolute basics of being able to `var pl = require('patternlab-node')(config);`. The big problem that remains is that most of the stuff that is ran from `builder/patternlab.js` (the `require`-ed file) is running from the working directory of `node_modules/patternlab-node/`, so this PR doesn't complete #221 but simply moves towards it and allows it to work if you know what you're doing. The way I'm getting around this (for now) is with this:
```js
var config = fs.readFileSync('./config--pattern-lab.json');
var pl = require('patternlab-node')(config);
// get directory
var plnDir = path.dirname(require.resolve('patternlab-node/package.json'));
// save place
var originCwd = process.cwd();
// change to pl directory
process.chdir(plnDir);
// build it
pl.build(true);
// come …
```
=> Basics of being dependent and passing in config

builder/pattern_assembler.js, builder/patternlab.js, test/pattern_assembler_tests.js
Hey, I would like to submit a minor bugfix to v1.0.0 regarding [*Added ability to specify link.* urls inside data objects*](https://github.com/pattern-lab/patternlab-node/issues/171)
This minor refactor allows for pattern links insde `_data.json` as well as pattern `*.json` objects
Also notice the RegExp has been updated to only match `link\.[A-z0-9-_]` to avoid matching `link123something` or `link*something`
Changed: target to dev branch
=> bugfix: #171 pattern links inside base data object

Gruntfile.js, gulpfile.js
Addresses #252, #159 
**Summary of changes:**
This blacklists the UI chrome to exempt it from browsersync's snippet injection, meaning that the only thing it's glommed onto is the iframe itself and the stuff inside it. This should hopefully eliminate most of the spooky behavior that comes from BS, and in my testing, makes CSS injection and auto-page-refresh (upon editing pattern HTML) work correctly under both grunt & gulp.
**Bonus:** this also moves the browsersync badge to the lower right and chills it out some -- a request from my team that I think would be welcome to others.
=> Better browsersync

builder/parameter_hunter.js
Addresses #250 preliminary work
@bmuenzenmeyer I had been perusing parameter_hunter.js and think it's time to get rid of the eval() statement. I think this replacement is relatively simple, and complete at the same time. Please review.
=> Replacing eval with json.parse

builder/pattern_engines/engine_mustache.js
Addresses #250 (preliminary work)
Updating 2nd param for partialString.replace().
Old findPartialKeyRE:
`/{{>([ ])?([\w\-\.\/~]+)(:[A-z-_|]+)?(?:\:[A-Za-z0-9-_]+)?(?:(| )\(.*)?([ ])?}}/g`
New findPartialKeyRE:
`/{{>\s*([\w\-\.\/~]+)(\:[\w\-|]+)?(\:[\w\-]+)?(\s*\([^\)]*\))?\s*}}/g`
Since the capture group comprising ([\w\-\.\/~]+) used to be the 2nd capture group, but is now the 1st capture group, we need to update the 2nd param in partialString.replace() to '$1'.
=> fixing regex for replace operation in findPartialKey_new

builder/parameter_hunter.js, test/parameter_hunter_tests.js
Addresses #250 (preliminary work)
@bmuenzenmeyer Tightening up the regex for JSON parsing parameter submission. Needed better regex for single-quote wrapped keys. Also, don't need the m flag.
=> better regex for replacing single quotes

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG, README.md, builder/lineage_hunter.js, builder/list_item_hunter.js, builder/media_hunter.js, builder/object_factory.js, builder/parameter_hunter.js, builder/pattern_assembler.js, builder/pattern_exporter.js, builder/patternlab.js, builder/patternlab_grunt.js, builder/patternlab_gulp.js, builder/pseudopattern_hunter.js, builder/style_modifier_hunter.js, package.gulp.json, package.json
* #217 support for pattern type (atoms/molecules/etc) view all pages
* #262 Update destination of copied fonts
* #263 Improved parameter parsing inside parameter_hunter, with unit tests
=> Pattern Lab Node v1.1.3

Gruntfile.js, gulpfile.js
Add glob in the BrowserSync blacklist to match ?p= pattern URLs on the main UI chrome so BS won't load on both in the case where you select a specific pattern and then refresh the whole page.
We were having mysterious issues with a double BS badge appearing unpredictably, and it turns out this was the issue.
Would you prefer I create an issue and then refer to it in cases like this, or just do the PR?
EDIT: addresses #273
=> Fix double BrowserSync on whole-UI refresh after selecting pattern

builder/parameter_hunter.js, test/parameter_hunter_tests.js
Addresses #250 (preliminary work)
This converter to well-formed JSON will correctly account for different quoting schemes, as well as quotes within quotes for parameter values. Unit tested.
=> more robust parameter to json conversion

README.md, core/lib/lineage_hunter.js, core/lib/pattern_assembler.js, core/lib/patternlab.js, patternlab-config.json, test/lineage_hunter_tests.js, test/pattern_assembler_tests.js
* Pattern States are now assigned using the pattern key (atoms-colors), not the pattern name (colors). This change aligns with other uses of the key throughout Pattern Lab.
* Patterns inherit the lowest common denominator pattern state of their lineage.
* Pattern inheritance occurs only for patterns that define a pattern state themselves.
closes #203
=> Implement pattern state lowest common denominator

core/templates/partials/ishControls.mustache
- links in ishControls were pointing to pattern-lab.info, which is now just a Media Temple parking page
- now pointing to patternlab.io
=> fix documentation links in the header bar

core/lib/object_factory.js, core/lib/pattern_assembler.js, core/lib/pattern_engines/engine_handlebars.js, core/lib/pattern_engines/engine_mustache.js, core/lib/pattern_engines/engine_twig.js, core/lib/pattern_engines/engine_underscore.js
Hey, Brian -- this is an architectural change that requires engines' `renderPattern()` methods to be passed a full oPattern rather than just the extendedTemplate string. This came about because I wanted be able to print useful error messages in underscore templates, but realized that when an engine actually gets around to render time, it doesn't know what the file name of the pattern being rendered is, the pattern name, or really anything else about it except the template string itself.
So the solution proposed here is just to pass the full pattern object into renderPattern() methods. As before, the `renderPattern()` function in `pattern_assembler.js` is used as a compatibility shim so the UI can still render its "plain" mustache templates. Have a look at that to see if that feels too …
=> Dev 2.0 full pattern objects passed to engine render

core/lib/annotation_exporter.js, core/lib/ui_builder.js
Addresses part of https://github.com/pattern-lab/edition-node-gulp/issues/12
Adds back in support for the current style of annotations, reading in `annotations.js`, parsing it as JSON, and outputting to the new location. 
Work remaining includes understanding how to use a markdown file instead.
=> Annotations v1

core/lib/patternlab.js
Addresses #322 
Use mustache compiled header and footer sections.
=> View all pages for atoms, molecules, organisms have still some

core/lib/annotation_exporter.js, core/lib/ui_builder.js, package.json
Addresses https://github.com/pattern-lab/patternlab-node/issues/336
- uses paths construct to find css location
- passes unit tests.
- could not test in edition-node-gulp yet. will keep an eye on this feature.
=> 336 remove hardcoded path

core/lib/pattern_engines.js
@bmuenzenmeyer, check this out.
This should let us load engines from the core, or from whatever the "current" directory is. This isn't a perfect solution yet, because aside from checking the core, it assumes that the you're launching grunt/gulp/nodeunit/whatever from the root of your edition and looks for engine modules there. Has anyone ever *not* done it that way? Should we be more rigorous?
=> Load engines flexibly from either the current directory's node_modules

core/lib/object_factory.js, core/lib/ui_builder.js
Addresses #347
I'm fixing this blindly -- if this doesn't work, I'll set this up in a Windows VM and see what I can do.
Use Path tools and regex rather than the old-string length tomfoolery. Hopefully this gets us out of platform-specific path issues.
=> Hopefully fix #347. Use Path tools and regex instead of hackish

test/engine_handlebars_tests.js, test/engine_twig_tests.js, test/engine_underscore_tests.js
Addresses #352.
- Stop doing the hackish `return;` before the main body of code. My editor pointed out, I think rightly, that this is not okay. Instead, we do a check at the end and then wipe out the exports of the module.
- The check itself now uses the real engine loader as the source of truth, which I hope will be more accurate.
- We now pass tests!
There are some more alarming changes in the underscore test file, but all I did was remove the IIFE around the module body and clean stuff up.
=> Make the engine unit tests chill out if their engines aren't installed

.travis.yml, core/lib/list_item_hunter.js, test/files/_patterns/00-test/12-another-styled-atom.mustache, test/files/_patterns/00-test/13-listitem.mustache, test/list_item_hunter_tests.js
Addresses #356
* unit test to cover the scenario
* reset a retrieved patterns extendedTemplate when found
* cleaned up and clarified listitems mock object
=> 356 listitem bug

core/lib/list_item_hunter.js, core/lib/object_factory.js, core/lib/pattern_assembler.js, core/lib/pseudopattern_hunter.js, core/lib/ui_builder.js, test/pattern_assembler_tests.js
Addresses #368
* expanding links found in listitems.json
* improve writing of pseudopatterns to disc - no longer have the tilde in the paths
* moved the search for pseudo-pattern variants to processPatternsIterative. dont know why it wasnt always there
=> Add support to expand link.patternPartials inside listitems

core/lib/object_factory.js, core/lib/pattern_assembler.js, package.json, test/engine_mustache_tests.js, test/object_factory_tests.js, test/pattern_assembler_tests.js
Addresses #377 - Pattern Parameters Inconsistently Rendered
* semver bump for https://github.com/pattern-lab/patternengine-node-mustache/pull/1
* break out mustache tests into own file
* includes groundwork for https://github.com/pattern-lab/patternlab-node/issues/376 too
=> Pattern Lab Node 2.0.2

core/lib/annotation_exporter.js, package.json, test/annotation_exporter_tests.js, test/files/annotations.md, test/files/nav.md
Addresses #385
* read in *.md files ( not recursive )
* clobber annotations and write
* satisfies existing tests
=> fix for issue #385 - support foo.md inside _annotations

core/lib/ui_builder.js
Addresses #393 
Pass the sorted styleguidePatterns data structure to buildViewAllPages() rather than overwriting patternlab's main patterns data structure with the pared down list of patterns.
=> Pass the sorted styleguidePatterns data structure to buildViewAllPages()

core/lib/patternlab.js
Addresses https://github.com/pattern-lab/the-spec/issues/26
Accept an additional config to control the naming of output files with suffixes for rendered, rawTemplate, and makupOnly
=> Feature configurable suffixes

core/lib/lineage_hunter.js, core/lib/list_item_hunter.js, core/lib/parameter_hunter.js, core/lib/pattern_assembler.js, test/lineage_hunter_tests.js, test/parameter_hunter_tests.js, test/pattern_assembler_tests.js
Addresses #407 
@bmuenzenmeyer 
Mostly just simple name changes. This helps when grepping for one function vs the other.
Also includes minor updates to the getPartial function itself. One avoids string-concatenation and the hard-coded "mustache" extension. Another replaces `throw` with `console.error` because `throw` throws misleading messages when the error is nothing more than a match not being found.
=> Find partial to get partial

core/lib/patternlab.js
Addresses #418 
This just implements the behavior that we would expect if the user-editable header and footer were mandatory but missing for whatever reason. If this is off-spec or not the case, please ignore this and close #418.
I wrote this mostly because I had to to debug my own migration issue, so I thought I'd share. :)
=> Missing user-editable header / footer error handling.

core/lib/patternlab.js, core/lib/ui_builder.js
Addresses #408 
Processing, but hiding from the UI, underscore-prefixed directories, since they are processed in PHP, and there is nothing in the spec forbidding them.
=> processing-but-hiding-underscore-prefixed-dirs

core/lib/patternlab.js, package.json
=> Better handle missing outputfileSuffixes

core/lib/patternlab.js
Addresses #446 
Hey, it's a one-liner. We just drop the engine name into the pattern data block on the pattern's rendered html page. The UI can be updated to use it, but otherwise will ignore it.
See also:
* https://github.com/pattern-lab/styleguidekit-assets-default/issues/43
* https://github.com/pattern-lab/styleguidekit-assets-default/pull/44
Bonus: I believe this change is harmless even if support is missing in styleguidekit-assets-default. Likewise, I believe the proposed change to styleguidekit-assets-default is harmless even if this change isn't present.
=> Support patternengine name rather than file extension in the template tab

core/lib/pattern_assembler.js, core/lib/patternlab.js, core/lib/pseudopattern_hunter.js, core/lib/ui_builder.js, package.json, test/pattern_assembler_tests.js, test/pseudopattern_hunter_tests.js, test/ui_builder_tests.js
https://github.com/pattern-lab/patternlab-node/wiki/ChangeLog
=> Pattern Lab Node Core 2.5.0

core/lib/starterkit_manager.js, package.json
Addresses #462
- listStarterkits now fetches a list of repos 
- Returns a Promise<Array> with {name,url} per repo
=> Make listStarterkits return an array of repo objects

core/lib/pseudopattern_hunter.js, test/files/_patterns/00-test/474-pseudomodifier.mustache, test/files/_patterns/00-test/474-pseudomodifier~test.json, test/pseudopattern_hunter_tests.js
=> copy found partials when processing pseudo-patterns

core/lib/starterkit_manager.js
=> #490 Add proper javadoc comments to core/lib/starterkit_manager.js

core/lib/style_modifier_hunter.js
=> #491 Add proper javadoc comments to core/lib/style_modifier_hunter.js

Gruntfile.js, package.json, test/annotation_exporter_tests.js
Addresses #466
* Add support for tap based unit tests
* Create a tape grunt task to run the tests units
** Add the tape task to travis and build tasks
* Convert annotation_exporter_tests to use tap
=> Add tap support for unit tests

test/object_factory_tests.js
=> Convert object_factory_tests.js to use tap/tape

test/engine_handlebars_tests.js
=> Convert engine_handlebars_tests.js to use tape

test/engine_mustache_tests.js
=> Convert engine_mustache_tests.js to use tape

test/engine_twig_tests.js
Addresses #519  
- convert tests to use tape
=> Convert engine_twig_tests.js to use tape

test/engine_underscore_tests.js
Addresses #520  
- convert tests to tape
=> Convert engine_underscore_tests.js to use tape

.eslintrc, core/lib/patternlab.js
Addresses #541 
* Ask the linter to tolerate es6 syntax; all the es6 syntax herein was chosen to be compatible back to Node 4.4 
* Factor out writePatternFiles()
* Preserve the current scheme as the default formatter, and provide hooks for engines to be able to implement their own
* Add a hook for engines to be able to add files to the output if they need to
=> Engine hooks for file writing

core/lib/pattern_assembler.js
- Fix syntax of depth check fallback in case of files at depth 0.
When parsing files at the 0th level (e.g., markdown associated with 1st-level folders), this regex returns `undefined`. The`|| []` was meant to guard against checking `.length` of `undefined`, but was ineffective due to this missing a pair of parentheses.
Should I attempt to add a test for this, or is it simple enough to go in as-is?
=> Fix relativeDepth check

test/engine_handlebars_tests.js, test/files/_handlebars-test-patterns/00-atoms/00-global/10-at-partial-block.hbs, test/files/_handlebars-test-patterns/00-molecules/00-global/10-call-at-partial-block.hbs
Add  test cases for https://github.com/geoffp/patternengine-node-handlebars/issues/3
One of the tests should fail until this [PR](https://github.com/pattern-lab/patternengine-node-handlebars/pull/5) has been merged
=> Add test cases for @block-partial issue in Handlebars engine

core/lib/ui_builder.js
Minor change to fix this issue: https://github.com/pattern-lab/edition-node-gulp/issues/91
Updated the path to the plugins object.
=> Fixed the path to the plugins object. Issue 91 on the edition-node-gulp repo

core/lib/patternlab.js
When developing a patternlab-node plugin, I found it useful to have access to the loaded pattern engines as a property of the patternlab object.  This PR introduces an `engines` property to the `patternlab` object.
=> Expose the pattern engines as a property of the patternlab object

README.md
Addresses #
Simple update to url for up for grabs issues. Permalink change to include help wanted segment along with the up for grabs url segment.
=> Fix link to help wanted and up for grabs issues

core/lib/patternlab.js, package.json
=> Pattern Lab Node Core 2.7.1-alpha

core/lib/ui_builder.js
Combined with pattern-lab/styleguidekit-assets-default#53 , the existing JSON flag `ishControlsHide.views-all` can be respected (hiding the "All" nav item at the topmost level).
More specifically, this allows the nav template to access the hiding options set in the JSON `ishControlsHide` object. Previously this object was only accessible to the ish template.
=> Hide "All" nav item if JSON flag is set

core/lib/ui_builder.js
replace '/' with path.sep to work in both Windows and POSIX env
Addresses #596
Replacing forward slash with `path.sep` to match `pattern.relPath`
=> use path.sep to match omitted directories

core/lib/ui_builder.js
Addresses: Option of excluding sub pattern types from the styleguide
* Replicated omitPatternType for 'patternType/patternSubtype'
* Duplicated typePatterns as styleguideTypePatterns to seperate stylguide and nav menu creation.
=> Option of excluding sub pattern types from the styleguide

core/lib/pattern_assembler.js, core/lib/patternlab.js, core/lib/plugin_manager.js, package.json, patternlab-config.json, test/pattern_assembler_tests.js
Addresses #619
- removed setState() from pattern_assembler.js
- removed patternStates from this repo. 
- Will also remove patternStates from other repos
- Tests are passing.
=> Remove pattern states

core/lib/annotation_exporter.js, core/lib/json_copy.js, core/lib/list_item_hunter.js, core/lib/parameter_hunter.js, core/lib/pattern_assembler.js, core/lib/patternlab.js, core/lib/ui_builder.js, package.json
Addresses #637 
* Replaces JSON5 with the stock implementation of the JSON library
=> Revert JSON parsing to stock implementation

test/files/_patterns/00-test/00-foo.md, test/files/_patterns/00-test/01-bar.md, test/files/_patterns/00-test/03-styled-atom.md, test/lineage_hunter_tests.js, test/markdown_parser_tests.js
Fixed the broken Lineage Hunter unit test to load the patterns using the actual loader instead of trying to mock them out. The test MD files also seem to have been using `status` instead of `state`, so updated them as well (as per https://github.com/pattern-lab/the-spec/issues/16).
=> Fix broken unit test(s)

core/lib/pattern_engines.js, core/lib/patternlab.js
This is the simplest and least disruptive way I can think of to make engines configurable. If supported by each engine, call a function that injects the global pattern lab config into the closure scope of the engine so that engines can make configurable decisions.
@bramsmulders and I are thinking this is necessary to be able to configure the React engine -- the first use case being the ability to shut off client-side code generation if you don't need interactive components and / or are just using React components to make a static style guide. There should be some build speed benefit to doing that. 
This might also benefit the Handlebars engine, I seem to remember that it has some things you can configure.
See https://github.com/pattern-lab/patternengine-node-mustache/pull/8 for the …
=> Config access for pattern engines

core/lib/patternlab.js, test/files/_data/listitems.json, test/files/_patterns/00-test/paramMiddle.mustache, test/files/_patterns/00-test/paramParent.json, test/files/_patterns/00-test/paramParent.mustache, test/patternlab_tests.js, test/util/patternlab-config.json
adds unit test coverage for pattern-lab/edition-node-gulp#102
=> Issue 653 integration test

README.md
- URL was relative, so it didn't work
- Now it works
- :tada:
=> Fixing URL in Readme

core/lib/parameter_hunter.js
Fixes an issue whereby injecting list items via pattern parameters into patterns would throw syntax errors. E.g:
```
{{> molecules-select-with-information(
"sub-information": "Extra info about option 1",
"options": [{
"key": "1",
"label": "Option 1"
},
{
"key": "2",
"label": "Option 2"
},
{
"key": "3",
"label": "Option 3"
}],
"value": "1"
) }}
```
Error thrown without fix:
```
[patternlab:build] There was an error parsing JSON for 02-organisms/visits/add-visit.mustache
[patternlab:build] SyntaxError: Unexpected token } in JSON at position 43
at JSON.parse (<anonymous>)
at /Users/cjpitt/development/the92club/node_modules/patternlab-node/core/lib/parameter_hunter.js:271:28
at Array.forEach (native)
```
=> Attempt to parse the JSON to see if it is already well formed

README.md, core/lib/patternlab.js, package.json, test/files/_patterns/00-test/685-list.mustache, test/pattern_assembler_tests.js
Addresses #685
Summary of changes: Fix call to `dataLoader.loadDataFromFile()`, which adds the extension glob for us
=> Pattern Lab Node Core 2.11.1

core/lib/pattern_engines.js, test/pattern_engines_tests.js
=> Allow engines to support multiple extensions

.github/CONTRIBUTING.md
=> Updating Contribution Guidelines

core/lib/parameter_hunter.js, test/parameter_hunter_tests.js
Allow the use of link variables inside pattern parameters.
Addresses #688
The pattern parameters are run through `parse_data_links_specific` before rendering the pattern.
=> Add support for pattern parameter links

core/lib/patternlab.js
closes #614
Addresses #614 
Adds jsdocs to returned object. Some functions may require validation, but it's a start
=> document public API

README.md
Addresses #724
Summary of changes: Updated README
=> 724 readme

core/lib/ui_builder.js
What was happening is that the `theme` object from `patternlab-config.json` was getting put into `styleguide/data/patternlab-data.js` in both `config.theme` and as `theme`. I think it makes more sense to have settings declared in `config` be inside of that object. 
Relates to https://github.com/pattern-lab/styleguidekit-assets-default/issues/91
=> Removing redundant config.theme

core/lib/data_loader.js
Simple change to output the filename and error message of a failed parse to make the problem easier to find when there are multiple json files for a single pattern
=> More helpful errors

README.md
Addresses wrong package name post publish
add scoped package name
=> fix(README): Add scoped package to install instructions

README.md, core/lib/patternlab.js, package.json
=> fix(README): Fix broken link and whitespace

.travis.yml, core/lib/pattern_engines.js
=> Adding better traverse for pattern engines

core/lib/pseudopattern_hunter.js, test/files/_patterns/00-test/03-styled-atom.json, test/pseudopattern_hunter_tests.js
Addresses #711
pseudopattern_hunter is performing a dangerous lodash merge against the base pattern data
``` js
//extend any existing data with variant data
variantFileData = _.merge(currentPattern.jsonFileData, variantFileData);
```
resulting in the [mutation](https://lodash.com/docs/4.17.4#merge) of the `currentPattern.jsonFileData object`.
Luckily, we get around this elsewhere by using `jsonCopy` on the merged objects. 
I also verified this now using starterkit-mustache-demo.
(wrong data)
(wrong data)
(correct default data)
(correct override data)
=> pseudopatterns polluting base patterns

core/lib/patternlab.js, test/patternlab_tests.js
Addresses #749 
Adding a (static) function to the patternlab core to allow users to obtain a default config object
=> Adding getDefaultConfig function to core

core/lib/patternlab.js, package-lock.json, package.json, test/patternlab_tests.js
Addresses #751
Removes the first parameter (a callback) in the `build` and `patternsonly` methods, as they return promises anyway
=> feat(patternlabjs): Remove build callback

core/lib/exportData.js, core/lib/ui_builder.js, test/exportData_tests.js
Broke out `exportData` with initial coverage.
=> feat(exportData): Broke out file with unit test coverage

core/lib/asset_copy.js
Addresses #762 
Removed the basename append in `addDir` watcher
=> Fixes dir duplication when serving files

test/engine_react_tests.js, test/files/_react-test-patterns/00-atoms/00-general/HelloWorld.jsx
Involves #536.
This adds the first couple of unit tests for the React engine. Currently requires the `async-rendering` branch of `patternengine-node-react`.
=> First couple of unit tests for the React engine

core/index.js, core/lib/buildFooter.js, core/lib/patternlab.js, core/lib/processMetaPattern.js, core/lib/ui_builder.js
Use patterns created by processMetaPattern for rendering (instead of empty ones).
Addresses #766 
1. Set patternlab.userHead and patternlab.userFoot to their full patterns instead of just the extendedTemplate.
2. Replace empty patterns in render calls with full patterns.
=> Use patterns created by processMetaPattern for rendering

core/index.js, core/lib/changes_hunter.js, core/lib/loadPattern.js, test/changes_hunter_tests.js
Closes #790 
Explicitly append the known data filenames when searching for changes.
I think this was introduced in https://github.com/pattern-lab/patternlab-node/pull/634 when the extension was no longer used with `data_loader` (😎) but removed it from the caller (:bug:)
=> fix(loadPattern): Check proper data file paths for modification

core/index.js, core/lib/copier.js, core/lib/serve.js, core/lib/watchPatternLabFiles.js, test/watchPatternLabFiles_tests.js
Closes #793 
* Registers watches so they may be cleaned up on subsequent builds
* Only listens for events once, removing duplicative calls
=> Fix watches and event listener leaks

core/index.js, core/lib/patternlab.js
Addresses #717 
- Adding copy routine to copy pattern-specific JavaScript in place
=> Adding routine to copy js along pattern build

packages/core/src/index.js, packages/core/src/lib/help.js, packages/core/test/help_tests.js
- Split out `help`function from `core/src/index.js` to make it more versatile and uncluttered the main file
=> Split out help logs into an external function

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, README.md
Part of #815 
* Updates the top-level contribution guidelines and templates.
=> Update top-level documentation

packages/core/src/lib/changes_hunter.js
closes #794
supercedes of #802
=> fix(changes_hunter): guard for incrementalRebuild while watching

packages/cli/bin/archive.js, packages/cli/bin/install-edition.js, packages/cli/bin/utils.js, packages/cli/package-lock.json, packages/cli/package.json
Closes #864 
- Copies gulpfile.js from edition
- Updated dependencies
- Replaced fs-promise with fs-extra due to deprecation → https://www.npmjs.com/package/fs-promise
=> Copy gulpfile.js for edition-node-gulp

packages/cli/bin/install-edition.js
Closes #875
Adds break statements to CLI edition installation
=> fix(install): add break statements to install edition command

packages/core/src/lib/annotationExporter.js, packages/core/src/lib/exportData.js, packages/core/test/annotation_exporter_tests.js
Closes #836 
Read annotations.json if it exists. 
Else read annotations.js. 
Not sure if being able to read the old file is a necessary convenience. If not, that part of the code (the else statement) can easily be removed.
=> fix(package): Allow .json extension on annotations file (issue #836)

.prettierignore, packages/uikit-workshop/src/js/modal-styleguide.js
Checks to make sure the code panel-related <script> tag contains data before attempting to parse expected JSON. 
Partial fix to #761 as this should at least help prevent the current batch of JS errors from getting thrown till the larger data structure changes that caused this issue are identified and a fix rolled up. 
Related to #905 as Twig allows us to massage the data available at the template level to work around whatever data changes happened to cause this bug in the first place.
=> Partial Fix for Code Panel Toggle JS Errors on Master

packages/edition-twig/alter-twig.php
@EvanLovely just a tiny suggestion to your existing Twig PHP Engine PR #897 -- this just adds an example of how to enable Twig Debug mode (ie. `{{ dump(my_var) }}` ) for folks that aren't familiar with how exactly you switch that on or off with the new setup 😉
=> Add Example of Toggling Twig Debug Mode in New Twig PHP Engine

packages/uikit-workshop/.github/CONTRIBUTING.md, packages/uikit-workshop/gulpfile.js
Closes #913 
Summary of changes: 
- Updated uikit-workshop's CONTRIBUTING.md to mention npm scripts rather then gulp
- Removed `copyPublic` function and calls from uikit-workshop's gulpfile
=> [uikit-workshop] Remove copy-dist flag and logic from UIKit-Workshop

packages/engine-nunjucks/README.md, packages/engine-nunjucks/lib/engine_nunjucks.js, packages/engine-nunjucks/package.json
Creates a custom Nunjucks loader to resolve Pattern Lab paths. 
This replaces the hacky search and replace method that exists currently. Also fixes an issue with including patterns that contain includes.
=> Nunjucks loader to resolve Pattern Lab include paths

README.md, packages/cli/readme.md
Closes #940 
Clearer instructions and relationship with CLI
=> 940 simpler readme

.prettierignore, package.json
Closes #910 
Summary of changes: Updated .prettierignore and anded ignore path to npm prettier script
=> fix: Prettier should only format .js files

packages/uikit-workshop/package.json
Closes #964 
* Removes jshint from uikit-workshop
cc @c1rrus
=> fix(package): remove jshint

packages/core/src/lib/addPattern.js, packages/core/src/lib/patternlab.js
Closes #975 
find all patterns including pseudo patterns and sort them after
retrieving all patterns instead of inject them in the array working on
=> fix(patterns): find all patterns inlcuding pseudo patterns

.github/stale.yml
Updates Pattern Lab Node’s stalebot config to increase the amount of time before stalebot closes out a stale issue (as we’ve seen happen a couple times recently). 
This update will at least give folks a little bit more time to catch up on issues (30 days instead of 14) before auto closing.
=> Increase Time Before Stalebot Closes Issues

packages/core/src/lib/lineage_hunter.js
The Node Documentation says that [util._extend](https://nodejs.org/api/util.html#util_util_extend_target_source) function should not be used.
> util._extend(target, source)
> Added in: v0.7.5Deprecated since: v6.0.0
>
>   target <Object>
>   source <Object>
>
> Stability: 0 - Deprecated: Use Object.assign() instead.
>
> The util._extend() method was never intended to be used outside of internal Node.js modules. The community found and used it anyway.
>
> It is deprecated and should not be used in new code. JavaScript comes with very similar built-in functionality through Object.assign().
=> Removed deprecated extend function

packages/edition-twig/patternlab-config.json
This corrects the `edition-twig` uikit config paths that were posing a problem when it was used outside the monorepo!
See #1000 #897
=> fix(edition-twig): correct uikit paths in config

packages/uikit-workshop/dist/styleguide/js/patternlab-pattern.js, packages/uikit-workshop/dist/styleguide/js/patternlab-viewer.js, packages/uikit-workshop/webpack.config.js
Fixes 404 when running pattern lab from a non-root directory:
After PR:
- Made the uikit publicPath Relative
=> UIKit no longer requires the root directory

packages/live-server/index.js
Sets the content-length correctly based on the total number of SVGs contained in the document.
Closes #1011
=> Fix issues with multiple inline svgs in live-server injection

packages/core/src/lib/compose.js
Re-implements #948.   
I believe it was accidentally removed in https://github.com/pattern-lab/patternlab-node/commit/42bfe29aeaa68b956110f3b7fe88d6395cf98286#r33265705
=> Add cachebuster back to footer data

packages/cli/bin/inquiries/edition.js, packages/cli/bin/inquiries/starterkit.js, packages/cli/bin/install-edition.js, packages/edition-node/README.md, packages/edition-node/helpers/test.js, packages/edition-node/package.json, packages/edition-node/patternlab-config.json
@bradfrost's starterkit-handlebars-demo is not showing up during init
this used to be dynamic... but at some point i do not recall appears to be hardcoded.
```
cd to/monorepo/packages/cli
npm link
```
then
```
mkdir pl-test-1038
cd pl-test-1038
npm init -y
npm install @pattern-lab/cli
npm link @pattern-lab/cli
npx patternlab init
```
though these choices are made - the actual code (such as handlebars as the default wont likely be in place until this is released)
=> feat(starterkits): add starterkit-handlebars-demo

packages/starterkit-handlebars-demo/dist/css/style.css, packages/starterkit-handlebars-demo/package.json
* add css output to starterkit-handlebars-demo
* add simple build command to regen
related to https://github.com/pattern-lab/patternlab-node/issues/1043 - it's so easy to `npx node-sass` maybe that's a crutch we can rely on for a while
=> fix(starterkit): add css output and build command

packages/uikit-workshop/src/scripts/components/panels-viewer.js, packages/uikit-workshop/src/scripts/components/pl-viewport/pl-viewport.js
1. Fixes an issue in UIKit's Prism.js logic to correctly fall back to using `markup` for syntax highlighting when encountering an unsupported templating language. Addresses a recent bug reported by @thethomic on Gitter.
2. Ports over a recent UIkit fix from https://github.com/bolt-design-system/bolt which automatically defaults the viewport resizer to 100% the screen width the very first time PL is opened / if any custom viewport sizes haven't previously been set / when server-side rendering. Addresses one of the issues reported by @cbirdsong on Gitter a couple days ago.
=> UIKit Bug Fixes

packages/cli/bin/install-starterkit.js, packages/cli/bin/utils.js
Closes #1065 
- Drop the check that the package name of the starterkit begins with `@pattern-lab/` namespace.
=> Let any package be installed as a Patternlab starterkit.

packages/cli/bin/inquiries/starterkit.js
Added starterkit-handlebars-vanilla to the list of available starterkits; updated some formatting
=> Add starterkit-handlebars-vanilla to CLI

packages/development-edition-engine-handlebars/patternlab-config.json, packages/uikit-workshop/src/sass/scss/04-components/_pattern.scss, packages/uikit-workshop/src/scripts/components/pl-header/pl-header.scss, packages/uikit-workshop/src/scripts/components/pl-logo/pl-logo.scss
- Updates the Handlebars demo's default pattern config to fix the "empty" page that initially shows up.
- Adds a small amount of inner padding to partially address #1062
- Reduces the global header shadow size just a tad + reduces the max logo height to make the global header's default height a bit more reasonable
=> Fix Handlebars Demo's defaultPattern + Minor UIKit Tweaks

packages/uikit-workshop/package.json
Updates the UIKit package.json to tell NPM to publish the auto-generated `dist` folder when publishing. Fixes the missing “dist” folder on NPM reported by @thethomic!
=> fix: publish auto-generated “dist” folder when publishing to NPM

core/lib/pattern_exporter.js, patternlab-config.json
**Use Case**: We use pattern-lab to create a rough design, then export all of our styles and patterns to a rails web application. This PR seeks to make the export more user-friendly by: 
1. Allowing us to export raw patterns (.mustache files) which can be interpreted by the ruby mustache template engine.
2. Preserving directory structure of our atoms/molecules/etc... such that we don't have _too_ much directory hierarchy, but one level deeper than just a flat directory structure.
3. Allowing us to easily specify that we want _all_ patterns to be exported, rather than having to manually specify each one (as our designs are in flux constantly right now, and there are many changes).
- Add capability to export all patterns via a flag in `patternlab-config.json`.
- Add …
=> Add pattern export all

packages/core/patternlab-config.json, packages/development-edition-engine-handlebars/patternlab-config.json, packages/edition-node-gulp/patternlab-config.json, packages/edition-node/patternlab-config.json, packages/edition-twig/patternlab-config.json
related to #601 
adds the new default options to each edition
=> feat(config): add new default pattern export options

packages/uikit-workshop/src/sass/pattern-lab.scss, packages/uikit-workshop/src/sass/scss/01-abstracts/_mixins.scss, packages/uikit-workshop/src/sass/scss/04-components/_breadcrumbs.scss, packages/uikit-workshop/src/sass/scss/04-components/_pattern-info.scss, packages/uikit-workshop/src/sass/scss/04-components/_tabs.scss, packages/uikit-workshop/src/sass/scss/05-themes/_light-theme.scss, packages/uikit-workshop/src/scripts/components/pl-nav/pl-nav.js, packages/uikit-workshop/src/scripts/components/pl-nav/pl-nav.scss, packages/uikit-workshop/src/scripts/lit-components/pl-button/pl-button.scss, packages/uikit-workshop/src/scripts/lit-components/pl-drawer/pl-drawer.scss, packages/uikit-workshop/src/scripts/lit-components/pl-header/pl-header.js, packages/uikit-workshop/src/scripts/lit-components/pl-header/pl-header.scss, packages/uikit-workshop/src/scripts/lit-components/pl-logo/pl-logo.scss, packages/uikit-workshop/src/scripts/lit-components/pl-toggle-layout/pl-toggle-layout.scss, packages/uikit-workshop/src/scripts/lit-components/pl-tools-menu/pl-tools-menu.scss, packages/uikit-workshop/src/scripts/lit-components/pl-viewport-size-list/pl-viewport-size-list.scss, packages/uikit-workshop/src/scripts/lit-components/pl-viewport/pl-viewport.scss, packages/uikit-workshop/src/scripts/patternlab-pattern.js
Minor UIKIt fixes I had actually originally thought were part of #1094 but mistakenly overlooked (sorry @bmuenzenmeyer!)
These updates include things like:
- Nav updates to try to get more predictable Nav opening / closing behavior
- CSS updates to remove the "boxiness" of the updated Viewport styles by adding a more subtle solid color background + removing the shadow around the Viewport itself
- Minor CSS fixes to the code panel / drawer to avoid content getting chopped off (especially on smaller screen sizes)
- Logo sizing fix for older versions of IE 11
- IE 11 fix for the viewport resizer background position being a bit off
=> Follow-up UIKit Fixes 

packages/uikit-workshop/src/sass/scss/02-base/_body.scss
CSS hotfix for IE 11 to address the main PL container height collapsing.
=> UIKIt CSS Hotfix for IE 11

packages/uikit-workshop/src/sass/pattern-lab.scss, packages/uikit-workshop/src/sass/scss/04-components/_tabs.scss
Small UIKIt CSS fix to address a Firefox rendering quirk reported by @thethomic that was causing the code panel contents to spill out of the container. 
Closes #1100
=> UIKit Fix: Code Panel Overflow Fix for Firefox

packages/uikit-workshop/src/scripts/patternlab-viewer.modern.js
Hotfix workaround to address a gap in our polyfill strategy. Basically the latest version of Edge supports ES modules but NOT custom elements, hence doesn't load the necessary polyfills that non-ES module supporting browsers would normally get.
We need to test and confirm that this workaround works as expected in other modern browsers (Chrome, Safari, FF) — quick testing in Chrome looked fine but just want to double-check before releasing.
Closes #1104
=> UIKit Polyfill Hotfix for Edge

packages/uikit-workshop/package.json
As github might be inaccessible / blocked on some environments (for whatever/security reasons), it's probably better to reference this dependency from NPM instead of Github as well, and solve the problem of referencing to the beta version by its exact upper version number.
Closes #
"html-webpack-plugin" dependency is being retrieved via NPM instead of Github.
=> chore: UIKit - referencing 'html-webpack-plugin' from NPM

packages/engine-twig-php/package.json, yarn.lock
This updates brings in [`@basalt/twig-renderer` v0.13.0](https://github.com/basaltinc/twig-renderer/releases/tag/v0.13.0) which updates Twig PHP to v1.42.2 and brings in the new `filter`, `map`, and `reduce` functions [just
added](https://symfony.com/blog/twig-adds-filter-map-and-reduce-features).
=> feat: upgrade Twig to use new filter, map, reduce

packages/engine-handlebars/package.json, yarn.lock
Updates Pattern Lab's Handlebars Engine to use the latest version of Handlebars (v4.5.3) per recommendation by @SingleSoulC_gitlab which appears to have addressed a few direct security issues based on the latest info showing up in Synk: https://snyk.io/vuln/npm:handlebars
=> Chore: Update Handlebars to v4.5.3

packages/uikit-workshop/src/scripts/lit-components/pl-header/pl-header.js, packages/uikit-workshop/src/scripts/lit-components/pl-logo/pl-logo.js
Closes #1111 
replaced `ratio` property by `width` and `height` properties for the themes logo customization.
=> feature: UIKit - logo: replaced ratio property #1111

packages/uikit-workshop/src/sass/scss/01-abstracts/_variables.scss, packages/uikit-workshop/src/sass/scss/04-components/_pattern.scss, packages/uikit-workshop/src/sass/scss/04-components/_tabs.scss, packages/uikit-workshop/src/sass/scss/04-components/_text-passage.scss, packages/uikit-workshop/views-twig/partials/patternSection.twig, packages/uikit-workshop/views/partials/patternSection.mustache
Summary of changes: fixing some a11y issues on the overview pages.
- The text colors used for some textual parts weren't at least following the 4.5 convention for AA compatibility on the white page background.
- Missing description of that complementary icon fixed by hiding this element via `aria-hidden`
=> Fix: a11y issues on overview pages

packages/engine-twig-php/lib/engine_twig_php.js
Closes #1117 
https://github.com/pattern-lab/patternlab-node/issues/1117
The Php Twig engine can now be fully configured. Any configuration in patternlab-config.engines.twig will be passed down to the twig renderer package.
=> feat: pass additional configuration into twig-php engine

packages/cli/bin/inquiries/edition.js, packages/cli/bin/inquiries/starterkit.js
Closes #1119 
Implements most of the changes discussed. I think there is still value in asking for a directory, especially with the default being CWD.
=> feat(cli): make options more user friendly

packages/engine-twig-php/package.json
Updates `engine-twig-php`'s dependency on `@basalt/twig-renderer` from v0.13.0 to [v0.13.1](https://github.com/basaltinc/twig-renderer/releases/tag/v0.13.1). This fix resolves an issue when using Pattern Lab in a Docker container where it doesn't have permissions to write to certain directories. That functionality wasn't critical (only used for keeping track of ports handed out) and could be kept in-memory - which is what this update does. Also it removes a dependency! Would appreciate a speedy merge & release on this as it's causing some errors for one of our clients using Pattern Lab 😁 🙏
=> fix: update twig-renderer

packages/uikit-workshop/src/scripts/lit-components/pl-viewport/pl-viewport.js
- Consolidates the iFrame routing logic to be less complex. Not a complete re-write here but definitely a bit less code than where we were previously at 
- Patches up some annoying browser history issues when going forward / backward
- Adds "psuedo-404" support so trying to navigate to a Pattern Lab URL for a pattern that doesn't exist (ex. `http://localhost:3000/?p=atoms-foobar`) or clicking on a broken link within Pattern Lab should now take you to a simple 404 error message + link back to your main default page (see GIF above^) CC @thethomic
=> Refactor Iframe Routing Logic + Add Psuedo-404 Support

packages/uikit-workshop/src/scripts/lit-components/pl-viewport-size/pl-viewport-size.js, packages/uikit-workshop/src/scripts/lit-components/pl-viewport/pl-viewport.scss
Updates the iFrame resizer UI so the resizer handle no longer shows up when the iframe is "full width" -- per feedback / recommendation from @bradfrost 😉
=> Update Pattern Lab's iframe resizer UI to be hidden when iframe is full width

packages/development-edition-engine-twig/.gitignore, packages/development-edition-engine-twig/CHANGELOG.md, packages/development-edition-engine-twig/README.md, packages/development-edition-engine-twig/package.json, packages/development-edition-engine-twig/patternlab-config.json, packages/development-edition-engine-twig/source/.gitignore, packages/engine-twig/README.md, packages/engine-twig/lib/engine_twig.js, packages/engine-twig/package.json, packages/starterkit-twig-demo/dist/_macros/forms.twig, packages/starterkit-twig-demo/dist/_patterns/03-templates/03-article-2col.twig, yarn.lock
Closes #285
* switched the dependency from [`node-twig`](https://www.npmjs.com/package/node-twig) to [`twing`](https://www.npmjs.com/package/twing)
Todo:
* a lot of testing
=> [WIP] feat: switch engine-twig to use twing rather than node-twig

packages/engine-twig-php/lib/engine_twig_php.js, packages/engine-twig-php/package.json
Before these changes, when a Twig syntax error was encountered (like using an incorrect function or filter), the error message would be displayed in the Terminal output but would say the build happened ok. The error messages from the Twig Renderer come out like "Error trying to render "01-components/card/05-card.twig". Unknown "render" filter.". After these changes, it displays the error message and then exits non-zero, which stops the output right where the dev can see the issue (either in watch mode or in CI builds).
=> fix: actually exit build when Twig render fails

packages/cli/bin/scaffold.js
Closes #1142 
In my testing of production, running `npm init patternlab` prompts you to choose a directory,
If you choose to specify a directory (assuming to create a new one, in this case, we check for the presence of a `package.json` but then don't use that same path to run `npm init` if one is not found. Sure enough, the `package.json` is created in the calling directory, not the new one.
This change Attempts to set current working directory prior to project init.
I tried getting the scaffold tests to work but could not in limited time.
=> fix(cli): set current working directory before scaffolded npm init

packages/core/src/lib/loaduikits.js, packages/core/test/loaduitkits_tests.js
Closes #1104 
Filters out `uikit-polyfills` from `loaduikits.js`, so that the warning about its presence never occurs. 
Added test asserting behavior.
=> fix(core): do not warn about uikit-polyfills

packages/cli/bin/scaffold.js
Closes #1142 
fix(cli): ensure specified directory exists prior to scaffold
=> fix(cli): ensure specified directory exists prior to scaffold

packages/docs/src/docs/advanced-config-options.md
Summary of changes: corrected a simple typo in the config documentation part
=> chore(typo): corrected that typo in docs for config options

packages/uikit-workshop/src/scripts/components/pl-nav/pl-nav.js, packages/uikit-workshop/src/scripts/components/pl-nav/src/NavButton.js, packages/uikit-workshop/src/scripts/components/pl-nav/src/NavItem.js, packages/uikit-workshop/src/scripts/components/pl-nav/src/NavLink.js, packages/uikit-workshop/src/scripts/components/pl-nav/src/NavList.js, packages/uikit-workshop/src/scripts/components/pl-nav/src/NavTitle.js, packages/uikit-workshop/src/scripts/components/pl-nav/src/NavToggle.js, packages/uikit-workshop/src/scripts/components/pl-nav/src/PatternState.js, yarn.lock
This PR makes two basic changes to the Nav in Pattern Lab's UIKit:
1. It starts to tackle the overall Nav refactor I started in #1102 by breaking apart the existing Nav UI into smaller, more manageable pieces, but without any visual or functional changes. This should help make any additional Nav refactor work a lot more palatable.
2. It fixes the annoying bug of having overlapping dropdown menus (on larger screens while the Nav is in Horizontal mode).
=> Minor Nav Refactor + Fix for Overlapping Dropdown Menus

packages/starterkit-handlebars-demo/README.md
missed to replace mustache initially and incorrect `handlebars` two times (both in package name and URL)
=> chore(docs): some typos

packages/docs/src/_includes/components/logo.njk
- Changed the logo path from `https://patternlab.io/assets/icon-atom.svg` to `https://patternlab.io/images/icon-atom.svg`
=> Fix logo image path

packages/plugin-tab/dist/js/@pattern-lab-plugin-tab.js, packages/plugin-tab/src/snippet.js, packages/uikit-workshop/src/scripts/components/panels.js
Closes #1163
Related to #1155 #1156
Reverted parts to the previously used placeholders within the `/packages/plugin-tab/src/snippet.js` file, and modified `/packages/plugin-tab/dist/js/@pattern-lab-plugin-tab.js` accordingly by migrating some code to that file.
This would reenable defining one or more filetypes to display within the code panels again.
=> Fix plugin-tabs enabling multiple file formats #1163
